import Head from "next/head";
import Header from "../components/template/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <Header />
      </main>
    </div>
  );
}
